set_davis_time:
get_davis_time:
get_raw_data:
get_info:
set_yearly_rain:
  fields:
    rain_clicks:
      required: true
      example: 500
      selector:
        number:
set_archive_period:
  fields:
    archive_period:
      required: true
      example: 10
      selector:
        select:
          options:
            - "1"
            - "5"
            - "10"
            - "15"
            - "30"
            - "60"
            - "120"
set_rain_collector:
  fields:
    rain_collector:
      required: true
      example: "0.2 mm"
      selector:
        select:
          options:
            - "0.01\""
            - "0.2 mm"
            - "0.1 mm"
set_barometer_calibration:
  fields:
    elevation:
      required: true
      example: 132
      selector:
        number:
          min: -2000
          max: 15000
          unit_of_measurement: "ft"
    barometer:
      required: false
      example: 29.491
      selector:
        number:
          min: 0
          max: 32.5
          step: 0.001
          unit_of_measurement: "inHg"
get_eeprom:
  fields:
    address:
      required: true
      example: "2B"
      selector:
        text:
    size:
      required: true
      example: 1
      selector:
        number:
          min: 1
          max: 256
set_eeprom:
  fields:
    address:
      required: true
      example: "2B"
      selector:
        text:
    data:
      required: true
      example: "13"
      selector:
        text:
set_console_lamps:
  fields:
    state:
      required: true
      example: true
      selector:
        boolean:
clear_alarms:
