set_davis_time:
  fields:
    entry_id: &entry_id
      required: false
      selector:
        config_entry:
          integration: davis_vantage
get_davis_time:
  fields:
    entry_id: *entry_id
get_raw_data:
  fields:
    entry_id: *entry_id
get_info:
  fields:
    entry_id: *entry_id
set_yearly_rain:
  fields:
    entry_id: *entry_id
    rain_clicks:
      required: true
      example: 500
      selector:
        number:
set_archive_period:
  fields:
    entry_id: *entry_id
    archive_period:
      required: true
      example: 10
      selector:
        select:
          options:
            - "1"
            - "5"
            - "10"
            - "15"
            - "30"
            - "60"
            - "120"
set_rain_collector:
  fields:
    entry_id: *entry_id
    rain_collector:
      required: true
      example: "0.2 mm"
      selector:
        select:
          options:
            - "0.01\""
            - "0.2 mm"
            - "0.1 mm"
set_barometer_calibration:
  fields:
    entry_id: *entry_id
    elevation:
      required: true
      example: 132
      selector:
        number:
          min: -2000
          max: 15000
          unit_of_measurement: "ft"
    barometer:
      required: false
      example: 29.491
      selector:
        number:
          min: 0
          max: 32.5
          step: 0.001
          unit_of_measurement: "inHg"
get_eeprom:
  fields:
    entry_id: *entry_id
    address:
      required: true
      example: "2B"
      selector:
        text:
    size:
      required: true
      example: 1
      selector:
        number:
          min: 1
          max: 256
set_eeprom:
  fields:
    entry_id: *entry_id
    address:
      required: true
      example: "2B"
      selector:
        text:
    data:
      required: true
      example: "13"
      selector:
        text:
set_console_lamps:
  fields:
    entry_id: *entry_id
    state:
      required: true
      example: true
      selector:
        boolean:
clear_alarms:
  fields:
    entry_id: *entry_id
run_test:
  fields:
    entry_id: *entry_id
get_station_type:
  fields:
    entry_id: *entry_id
rxtest:
  fields:
    entry_id: *entry_id
get_receivers:
  fields:
    entry_id: *entry_id
get_calibrated_values:
  fields:
    entry_id: *entry_id
set_calibrated_values:
  fields:
    entry_id: *entry_id
    data:
      required: true
      example: "0000000000000000000000000000000000000000000000000000000000000000000000000000000000"
      selector:
        text:
set_yearly_et:
  fields:
    entry_id: *entry_id
    et_hundredths:
      required: true
      example: 2483
      selector:
        number:
